## Configuration for the training, evaluation
## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT700*/*.pt
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT700_1/QCD_HT700_1-2018-5.pt

    xsec: 6330
    ngen: 48158738


  - name: 4top
    label: 1
    path: /users/yewzzang/TTTT_TuneCP5_13TeV-amcatnlo-pythia8/4top_dump_ex2/220323_084833/h5_2/4top_ex2_delphes_4.pt

    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
