## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/HT700*/*99.h5
    xsec: 6330
    ngen: 48158738
  - name: QCD1000
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/HT1000*/*99.h5
    xsec: 1090
    ngen: 14353647
  - name: QCD1500
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/HT1500*/*99.h5
    xsec: 99.1
    ngen: 10955087
  - name: QCD2000
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/HT2000/*99.h5
    xsec: 20.2
    ngen: 5475677

  - name: 4top
    label: 1
#     path: /users/yewzzang/TTTT_TuneCP5_13TeV-amcatnlo-pythia8/*/*/h5_3/*1.pt
    path : /users/yewzzang/data_graph/h5/4top/*/*99.h5
    xsec: 0.012
    ngen: 11952188

#   - name: ttbar
#     label: 1
#     path: /users/yewzzang/data_graph/pt/ttbar_weight_210719/noedge/*.pt
# #     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*.h5
#     xsec: 377.96
#     ngen: 333332000 

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
