## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/alledge/HT700*/*.h5
    xsec: 6330
    ngen: 48158738
  - name: QCD1000
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/alledge/HT1000*/*.h5
    xsec: 1090
    ngen: 14353647
  - name: QCD1500
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/alledge/HT1500*/*.h5
    xsec: 99.1
    ngen: 10955087
  - name: QCD2000
    label: 0
    path: /users/yewzzang/data_graph/h5/QCD/alledge/HT2000/*.h5
    xsec: 20.2
    ngen: 5475677

  - name: 4top
    label: 1
    path : /users/yewzzang/data_graph/h5/4top/alledge_w1/*/*.h5
    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
