## Configuration for the training, evaluation
samples:
  - name: ttbar
    label: 0
    path: /users/yewzzang/data_graph/h5/ttbar/noedge_w2_r_fea4/*.h5
    xsec: 377.96
    ngen: 333332000 

  - name: 4top
    label: 1
    path : /users/yewzzang/data_graph/h5/4top/noedge_w2/*/*.h5
    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
