## Configuration for the training, evaluation
samples:
  - name: 4top
    label: 1
    path : /users/yewzzang/data_graph/h5/4top/noedge/ex1_v2_210520_0/*9.h5
    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
