## Configuration for the training, evaluation
samples:
  
  - name: 4top
    label: 2
    path: /users/yewzzang/TTTT_TuneCP5_13TeV-amcatnlo-pythia8/4top_dump_ex1/220324_055935/graph/4top_22/4top_ex1_9*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_weight_210709/*/*.pt
    xsec: 0.012
    ngen: 11952188
    #####2849104

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.75, 0.25] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
